version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      # 请修改以下redis和mongodb的配置
      ACCOUNT: admin
      PASSWORD: admin
      REDIS_IP: 192.168.47.168
      REDIS_PORT: 6378
      REDIS_PWD: pwd
      MONGO_IP: 192.168.47.168
      MONGO_PORT: 27018
      MONGO_USER: scan
      MONGO_PWD: 123456
      MONGO_DB_NAME: portscan
